# Generated by Django 5.0.6 on 2024-06-14 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertylandlord',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
